name: Hello World

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: echo 'Hello World'

      - name: Show Date
        run: date

      - name: List Directory
        run: ls -l